#!/usr/bin/env python3
"""Derive the launch-animation assets from the owner-supplied logo.

Input : assets/brand/logo-transparent.png (the current logo, unmodified)
Output: three layer images sharing one canvas (upper ribbon, lower ribbon,
        green core) that composite back to the logo (edges anti-aliased), plus the
        silhouette outlines used for the blueprint wireframe phase.

Requires: pillow, numpy, opencv-python-headless.
Run from the repository root:  python3 scripts/brand/build_launch_assets.py
"""
from pathlib import Path

import cv2
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "assets/brand/logo-transparent.png"
RES = ROOT / "android/app/src/main/res/drawable-nodpi"
KT = ROOT / "android/app/src/main/kotlin/app/selvard/ui/launch/LogoGeometry.kt"
PAD = 8
MIN_AREA = 5000  # drops the stray cut-out pixels around the logo


def largest_components(mask):
    n, lab, stats, cent = cv2.connectedComponentsWithStats(mask.astype(np.uint8), connectivity=8)
    return [(lab == i, cent[i]) for i in range(1, n) if stats[i, cv2.CC_STAT_AREA] >= MIN_AREA]


def smooth_layer(rgb, mask, x0, y0, x1, y1):
    """Anti-aliased alpha (the source alpha is binary) with de-haloed edge colour."""
    m = mask[y0:y1, x0:x1].astype(np.uint8)
    col = rgb[y0:y1, x0:x1].copy()
    k = np.ones((3, 3), np.uint8)
    inner = cv2.erode(m, k, iterations=2)
    band = (cv2.dilate(m, k, iterations=3) - inner).astype(np.uint8)
    col = cv2.inpaint(np.where(inner[..., None] > 0, col, 0).astype(np.uint8), band, 3, cv2.INPAINT_TELEA)
    # The source alpha is binary and slightly ragged: soften, then re-steepen for a crisp AA edge.
    soft = np.clip((cv2.GaussianBlur(m.astype(np.float32), (0, 0), 3.0) - 0.3) / 0.4, 0, 1)
    alpha = soft * soft * (3 - 2 * soft) * 255
    smooth_mask = (soft > 0.5).astype(np.uint8)
    return np.dstack([col, alpha]).astype(np.uint8), smooth_mask


def outline_path(m):
    cs, _ = cv2.findContours(m, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
    c = max(cs, key=cv2.contourArea)[:, 0, :].astype(np.float32)
    k = 9
    ext = np.vstack([c[-k:], c, c[:k]])
    sm = np.stack([np.convolve(ext[:, i], np.ones(k) / k, mode="same") for i in (0, 1)], 1)[k:-k]
    poly = cv2.approxPolyDP(np.ascontiguousarray(sm, dtype=np.float32).reshape(-1, 1, 2), 0.4, True)[:, 0, :]
    pts = " ".join(f"{'M' if i == 0 else 'L'}{x:.1f} {y:.1f}" for i, (x, y) in enumerate(poly))
    return pts + " Z", len(poly)


def main():
    im = np.array(Image.open(SRC).convert("RGBA"))
    rgb, alpha = im[..., :3], im[..., 3] > 128
    g = rgb.astype(int)
    green = alpha & (g[..., 1] > g[..., 0] + 25) & (g[..., 1] > g[..., 2] - 10)
    core = largest_components(green)
    ribbons = largest_components(alpha & ~green)
    assert len(core) == 1 and len(ribbons) == 2, (len(core), len(ribbons))
    ribbons.sort(key=lambda r: r[1][0] + r[1][1])  # upper-left first
    layers = {"logo_ribbon_upper": ribbons[0][0], "logo_ribbon_lower": ribbons[1][0], "logo_core": core[0][0]}

    union = np.any(list(layers.values()), axis=0)
    ys, xs = np.where(union)
    x0, x1 = max(xs.min() - PAD, 0), min(xs.max() + PAD + 1, im.shape[1])
    y0, y1 = max(ys.min() - PAD, 0), min(ys.max() + PAD + 1, im.shape[0])
    RES.mkdir(parents=True, exist_ok=True)
    paths = {}
    for name, mask in layers.items():
        rgba, m = smooth_layer(rgb, mask, x0, y0, x1, y1)
        Image.fromarray(rgba, "RGBA").save(RES / f"{name}.webp", lossless=True, quality=100, method=6)
        paths[name] = outline_path(m)
        print(name, rgba.shape, "outline points:", paths[name][1])

    w, h = x1 - x0, y1 - y0
    cys, cxs = np.where(core[0][0])
    core_cx, core_cy = (cxs.min() + cxs.max()) / 2 - x0, (cys.min() + cys.max()) / 2 - y0
    def chunked(data, width=100):
        parts = [data[i : i + width] for i in range(0, len(data), width)]
        return " +\n".join(f'        "{part}"' for part in parts)

    body = "\n".join(
        f'    const val {n.upper().replace("LOGO_", "")}: String =\n{chunked(p)}' for n, (p, _) in paths.items()
    )
    KT.write_text(
        "package app.selvard.ui.launch\n\n"
        "/**\n * Generated by scripts/brand/build_launch_assets.py from assets/brand/logo-transparent.png.\n"
        " * Coordinates are pixels in the shared layer canvas; do not edit by hand.\n */\n"
        f"internal object LogoGeometry {{\n    const val WIDTH = {w}f\n    const val HEIGHT = {h}f\n"
        f"    const val CORE_CENTER_X = {core_cx:.1f}f\n    const val CORE_CENTER_Y = {core_cy:.1f}f\n\n{body}\n}}\n"
    )
    print("canvas", w, h)


if __name__ == "__main__":
    main()
