// Generates android/app/src/main/kotlin/app/selvard/ui/design/SelvardIcons.kt
// from Lucide (ISC license, https://lucide.dev). Run: node scripts/ui/build_icons.mjs
// Only the icons listed below are embedded; nothing is fetched at runtime.
import { writeFileSync } from "node:fs";

const VERSION = "0.468.0";
const ICONS = {
  Home: "house",
  Shield: "shield",
  ShieldCheck: "shield-check",
  ShieldAlert: "shield-alert",
  ShieldOff: "shield-off",
  Timeline: "history",
  Person: "user-round",
  Settings: "settings",
  Link: "link",
  Globe: "globe",
  Wifi: "wifi",
  Apps: "layout-grid",
  Eye: "eye",
  Mail: "mail",
  Card: "credit-card",
  Folder: "folder",
  Key: "key-round",
  ChevronRight: "chevron-right",
  ChevronDown: "chevron-down",
  Check: "check",
  Warning: "triangle-alert",
  Blocked: "octagon-x",
  Unknown: "circle-help",
  Lock: "lock",
  Info: "info",
  Search: "search",
  Paste: "clipboard-paste",
  Refresh: "refresh-cw",
  Trash: "trash-2",
  Power: "power",
  Close: "x",
  ArrowRight: "arrow-right",
  Phone: "smartphone",
  Bell: "bell",
  Clock: "clock",
  Fingerprint: "fingerprint",
  Message: "message-circle",
  Camera: "camera",
  Mic: "mic",
  MapPin: "map-pin",
  Database: "database",
  Activity: "activity",
};

const attr = (tag, name) => {
  const m = new RegExp(`${name}="([^"]*)"`).exec(tag);
  return m ? m[1] : null;
};
const num = (tag, name, dflt = 0) => {
  const v = attr(tag, name);
  return v === null ? dflt : parseFloat(v);
};
const f = (n) => Number(n.toFixed(3)).toString();

function toPaths(svg) {
  const out = [];
  for (const tag of svg.match(/<(path|circle|rect|line|polyline|polygon|ellipse)\b[^>]*>/g) ?? []) {
    const kind = /<(\w+)/.exec(tag)[1];
    if (kind === "path") out.push(attr(tag, "d"));
    else if (kind === "circle") {
      const cx = num(tag, "cx"), cy = num(tag, "cy"), r = num(tag, "r");
      out.push(`M${f(cx - r)} ${f(cy)}a${f(r)} ${f(r)} 0 1 0 ${f(2 * r)} 0a${f(r)} ${f(r)} 0 1 0 ${f(-2 * r)} 0`);
    } else if (kind === "ellipse") {
      const cx = num(tag, "cx"), cy = num(tag, "cy"), rx = num(tag, "rx"), ry = num(tag, "ry");
      out.push(`M${f(cx - rx)} ${f(cy)}a${f(rx)} ${f(ry)} 0 1 0 ${f(2 * rx)} 0a${f(rx)} ${f(ry)} 0 1 0 ${f(-2 * rx)} 0`);
    } else if (kind === "rect") {
      const x = num(tag, "x"), y = num(tag, "y"), w = num(tag, "width"), h = num(tag, "height");
      const rx = Math.min(num(tag, "rx", num(tag, "ry")), w / 2), ry = Math.min(num(tag, "ry", rx), h / 2);
      out.push(
        `M${f(x + rx)} ${f(y)}h${f(w - 2 * rx)}a${f(rx)} ${f(ry)} 0 0 1 ${f(rx)} ${f(ry)}v${f(h - 2 * ry)}` +
          `a${f(rx)} ${f(ry)} 0 0 1 ${f(-rx)} ${f(ry)}h${f(-(w - 2 * rx))}a${f(rx)} ${f(ry)} 0 0 1 ${f(-rx)} ${f(-ry)}` +
          `v${f(-(h - 2 * ry))}a${f(rx)} ${f(ry)} 0 0 1 ${f(rx)} ${f(-ry)}z`,
      );
    } else if (kind === "line") {
      out.push(`M${f(num(tag, "x1"))} ${f(num(tag, "y1"))}L${f(num(tag, "x2"))} ${f(num(tag, "y2"))}`);
    } else {
      const pts = attr(tag, "points").trim().split(/[\s,]+/).map(Number);
      let d = "";
      for (let i = 0; i < pts.length; i += 2) d += `${i === 0 ? "M" : "L"}${pts[i]} ${pts[i + 1]}`;
      out.push(kind === "polygon" ? d + "z" : d);
    }
  }
  return out;
}

let kt = `// GENERATED by scripts/ui/build_icons.mjs from Lucide ${VERSION} (ISC license). Do not edit by hand.
@file:Suppress("MaxLineLength", "LargeClass", "TooManyFunctions")

package app.selvard.ui.design

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

private fun lucide(name: String, vararg paths: String): ImageVector {
    val builder = ImageVector.Builder(name, 24.dp, 24.dp, 24f, 24f)
    paths.forEach { d ->
        builder.addPath(
            pathData = PathParser().parsePathString(d).toNodes(),
            stroke = SolidColor(Color.Black),
            strokeLineWidth = 2f,
            strokeLineCap = StrokeCap.Round,
            strokeLineJoin = StrokeJoin.Round,
        )
    }
    return builder.build()
}

/** Line icons (24dp grid, 2dp round stroke). Tint at the call site. */
object SelvardIcons {
`;

for (const [name, file] of Object.entries(ICONS)) {
  const res = await fetch(`https://unpkg.com/lucide-static@${VERSION}/icons/${file}.svg`);
  if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
  const paths = toPaths(await res.text());
  if (paths.length === 0) throw new Error(`${file}: no shapes parsed`);
  kt += `    val ${name}: ImageVector by lazy {\n        lucide(\n            "${name}",\n${paths
    .map((p) => `            "${p}",`)
    .join("\n")}\n        )\n    }\n`;
}
kt += "}\n";

const target = new URL("../../android/app/src/main/kotlin/app/selvard/ui/design/SelvardIcons.kt", import.meta.url);
writeFileSync(target, kt);
console.log(`wrote ${Object.keys(ICONS).length} icons`);
